#
# Copyright (c) 2022 by Pawel Tomulik <ptomulik@wp.pl>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE

Import('env')

doc = env.PDF('tikz-cnet-doc.tex')

env.Depends(doc, [

    'pgflibraryshapes.cnet.symbol.code.tex',
    'tikzlibraryshapes.cnet.symbol.code.tex',
    'tikzlibraryshapes.cnet.symbol.test.code.tex',

     # cnet symbols
    'pgflibraryshapes.cnet.code.tex',
    'tikzlibraryshapes.cnet.code.tex',

    'tikzlibraryshapes.cnet.car.code.tex',
    'pgflibraryshapes.cnet.car.code.tex',
    'tikzlibraryshapes.cnet.freezer.code.tex',
    'pgflibraryshapes.cnet.freezer.code.tex',
    'tikzlibraryshapes.cnet.laptop.code.tex',
    'pgflibraryshapes.cnet.laptop.code.tex',
    'tikzlibraryshapes.cnet.monitor.code.tex',
    'pgflibraryshapes.cnet.monitor.code.tex',
    'tikzlibraryshapes.cnet.rfwaves.code.tex',
    'pgflibraryshapes.cnet.rfwaves.code.tex',
    'tikzlibraryshapes.cnet.smartphone.code.tex',
    'pgflibraryshapes.cnet.smartphone.code.tex',

    # cisco symbols
    'pgflibraryshapes.cisco.code.tex',
    'tikzlibraryshapes.cisco.code.tex',

    'tikzlibraryshapes.cisco.100basethub.code.tex',
    'pgflibraryshapes.cisco.100basethub.code.tex',
    'tikzlibraryshapes.cisco.cloud.code.tex',
    'pgflibraryshapes.cisco.cloud.code.tex',
    'tikzlibraryshapes.cisco.firewall.code.tex',
    'pgflibraryshapes.cisco.firewall.code.tex',
    'tikzlibraryshapes.cisco.key.code.tex',
    'pgflibraryshapes.cisco.key.code.tex',
    'tikzlibraryshapes.cisco.laptop.code.tex',
    'pgflibraryshapes.cisco.laptop.code.tex',
    'tikzlibraryshapes.cisco.macintosh.code.tex',
    'pgflibraryshapes.cisco.macintosh.code.tex',
    'tikzlibraryshapes.cisco.macwoman.code.tex',
    'pgflibraryshapes.cisco.macwoman.code.tex',
    'tikzlibraryshapes.cisco.manwoman.code.tex',
    'pgflibraryshapes.cisco.manwoman.code.tex',
    'tikzlibraryshapes.cisco.pc.code.tex',
    'pgflibraryshapes.cisco.pc.code.tex',
    'tikzlibraryshapes.cisco.pcman.code.tex',
    'pgflibraryshapes.cisco.pcman.code.tex',
    'tikzlibraryshapes.cisco.router.code.tex',
    'pgflibraryshapes.cisco.router.code.tex',
    'tikzlibraryshapes.cisco.wirelessrouter.code.tex',
    'pgflibraryshapes.cisco.wirelessrouter.code.tex',
    'tikzlibraryshapes.cisco.workstation.code.tex',
    'pgflibraryshapes.cisco.workstation.code.tex',
])

env.PGFGen('pgflibraryshapes.cnet.car.code.tex.jinja')
env.PGFGen('pgflibraryshapes.cnet.freezer.code.tex.jinja')
env.PGFGen('pgflibraryshapes.cnet.laptop.code.tex.jinja')
env.PGFGen('pgflibraryshapes.cnet.monitor.code.tex.jinja')
env.PGFGen('pgflibraryshapes.cnet.rfwaves.code.tex.jinja')
env.PGFGen('pgflibraryshapes.cnet.smartphone.code.tex.jinja')

env.PGFGen('pgflibraryshapes.cisco.100basethub.code.tex.jinja')
env.PGFGen('pgflibraryshapes.cisco.cloud.code.tex.jinja')
env.PGFGen('pgflibraryshapes.cisco.firewall.code.tex.jinja')
env.PGFGen('pgflibraryshapes.cisco.key.code.tex.jinja')
env.PGFGen('pgflibraryshapes.cisco.laptop.code.tex.jinja')
env.PGFGen('pgflibraryshapes.cisco.macintosh.code.tex.jinja')
env.PGFGen('pgflibraryshapes.cisco.macwoman.code.tex.jinja')
env.PGFGen('pgflibraryshapes.cisco.manwoman.code.tex.jinja')
env.PGFGen('pgflibraryshapes.cisco.pc.code.tex.jinja')
env.PGFGen('pgflibraryshapes.cisco.pcman.code.tex.jinja')
env.PGFGen('pgflibraryshapes.cisco.router.code.tex.jinja')
env.PGFGen('pgflibraryshapes.cisco.wirelessrouter.code.tex.jinja')
env.PGFGen('pgflibraryshapes.cisco.workstation.code.tex.jinja')

# Local Variables:
# # tab-width:4
# # indent-tabs-mode:nil
# # End:
# vim: set syntax=python expandtab tabstop=4 shiftwidth=4:
