#
# Copyright (c) 2022 by Pawel Tomulik <ptomulik@wp.pl>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE

Import('env')

doc = env.PDF('tikz-cnet-doc.tex')

env.Depends(doc, [
    'pgflibraryshapes.cnet.symbol.code.tex',
    'tikzlibraryshapes.cnet.symbol.code.tex',
    'tikzlibraryshapes.cnet.symbol.test.code.tex',

     # cnet symbols
    'pgflibraryshapes.cnet.code.tex',
    'tikzlibraryshapes.cnet.code.tex',

    # cisco symbols
    'pgflibraryshapes.cisco.code.tex',
    'tikzlibraryshapes.cisco.code.tex',
])

symbols = [
    # cnet
    'cnet.car',
    'cnet.freezer',
    'cnet.laptop',
    'cnet.monitor',
    'cnet.rfwaves',
    'cnet.smartphone',
    'cnet.thermometer',
    'cnet.trafficlights',
    'cnet.workstation',
    # cisco
    'cisco.100basethub',
    'cisco.cloud',
    'cisco.firewall',
    'cisco.key',
    'cisco.laptop',
    'cisco.macintosh',
    'cisco.macwoman',
    'cisco.manwoman',
    'cisco.pc',
    'cisco.pcman',
    'cisco.router',
    'cisco.wirelessrouter',
    'cisco.workstation',
]

for symbol in symbols:
    env.Depends(doc, [
        f"pgflibraryshapes.{symbol}.code.tex",
        f"tikzlibraryshapes.{symbol}.code.tex",
    ])
    pgf = env.PGFGen(f"pgflibraryshapes.{symbol}.code.tex.jinja")
    env.Depends(pgf, f"../svg/{symbol}.svg")


# Local Variables:
# # tab-width:4
# # indent-tabs-mode:nil
# # End:
# vim: set syntax=python expandtab tabstop=4 shiftwidth=4:
